name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to AWS EC2
        runs-on: ubuntu-latest

    steps:
        name: Checkout code
        uses: actions/checkout@v4

        - name: Set up SSH key
            uses: webfactory/ssh-agent@v0.9.0
            with:
                ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/your-user/app-directory

            echo "Pulling latest changes from Git..."
            git pull origin main

            echo "Building Docker containers..."
            docker-compose down
            docker-compose build
            docker-compose up -d

            echo "Deployment complete."
          EOF
